### ISSUE TITLE
uint64/sint64 numbers are serialized as strings, uint32/sint32 are not

### ISSUE THREAD

**Issue by C0mbatwombat** [curioswitch/protobuf-jackson#19]
Hi :wave: 

I have noticed that 64 bit longs are serialized as JSON strings, while 32 bit integers are serialized as JSON numbers. Is this expected behaviour?

Test case:
```
message TestProto {
  optional uint64 v1 = 1;
  uint64 v2 = 2;

  optional uint32 v3 = 3;
  uint32 v4 = 4;

  optional sint64 v5 = 5;
  sint64 v6 = 6;

  optional sint32 v7 = 7;
  sint32 v8 = 8;

  optional double v9 = 9;
  double v10 = 10;

  optional float v11 = 11;
  float v12 = 12;
}


TestProto testObject = TestProto.newBuilder().setV1(1).setV2(2).setV3(3).setV4(4).setV5(5).setV6(6).setV7(7).setV8(8).setV9(9.0).setV10(10.0).setV11((float) 9.0).setV12((float) 10.0).build();
```

will serialize to:
```
{
  "v1" : "1",
  "v2" : "2",
  "v3" : 3,
  "v4" : 4,
  "v5" : "5",
  "v6" : "6",
  "v7" : 7,
  "v8" : 8,
  "v9" : 9.0,
  "v10" : 10.0,
  "v11" : 9.0,
  "v12" : 10.0
}
```

Would it be possible to add a flag/enum so everything serializes as either a string or a number?

Thanks!

**Comment by chokoswitch** [comment]
Hi @C0mbatwombat - this behavior is actually defined in the protobuf spec itself, while parsers will accept either, compliant serializers use string

https://protobuf.dev/programming-guides/proto3/#json

If upstream `JsonFormat` had a flag to control this behavior, we could replicate it here, but otherwise we wouldn't add a spec-breaking flag here since the goal of this project is to be a fast alternative to upstream but not add new fundamental features to it.

**Comment by C0mbatwombat** [comment]
Makes sense, thank you! Should have looked at the spec first :)
